"""Agregar modelo entidad

Revision ID: 06b9b33a3264
Revises: a12929156ea9
Create Date: 2023-09-17 21:55:25.154863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b9b33a3264'
down_revision: Union[str, None] = 'a12929156ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuit', sa.String(), nullable=True),
    sa.Column('razon_social', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entidades_cuit'), 'entidades', ['cuit'], unique=True)
    op.create_index(op.f('ix_entidades_id'), 'entidades', ['id'], unique=False)
    op.create_index(op.f('ix_entidades_razon_social'), 'entidades', ['razon_social'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entidades_razon_social'), table_name='entidades')
    op.drop_index(op.f('ix_entidades_id'), table_name='entidades')
    op.drop_index(op.f('ix_entidades_cuit'), table_name='entidades')
    op.drop_table('entidades')
    # ### end Alembic commands ###
