"""nueva relacion espacio usuario23

Revision ID: 0752bd582f0c
Revises: f90f718af1f6
Create Date: 2023-09-21 20:18:04.054805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0752bd582f0c'
down_revision: Union[str, None] = 'f90f718af1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
