"""crear modelo de solicitud de Dea

Revision ID: 0e9cc95d6ffe
Revises: c6d02cb491e8
Create Date: 2023-10-13 19:35:29.948948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9cc95d6ffe'
down_revision: Union[str, None] = 'c6d02cb491e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_deas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('latitud', sa.String(), nullable=False),
    sa.Column('longitud', sa.String(), nullable=False),
    sa.Column('atendido', sa.Boolean(), nullable=True),
    sa.Column('fecha_atendido', sa.DateTime(), nullable=True),
    sa.Column('espacio_obligado_id', sa.Integer(), nullable=False),
    sa.Column('dea_id', sa.Integer(), nullable=True),
    sa.Column('responsable_sede_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dea_id'], ['deas.id'], ),
    sa.ForeignKeyConstraint(['espacio_obligado_id'], ['espacios_obligados.id'], ),
    sa.ForeignKeyConstraint(['responsable_sede_id'], ['responsables_sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_deas_id'), 'solicitudes_deas', ['id'], unique=False)
    op.create_index(op.f('ix_solicitudes_deas_latitud'), 'solicitudes_deas', ['latitud'], unique=False)
    op.create_index(op.f('ix_solicitudes_deas_longitud'), 'solicitudes_deas', ['longitud'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_deas_longitud'), table_name='solicitudes_deas')
    op.drop_index(op.f('ix_solicitudes_deas_latitud'), table_name='solicitudes_deas')
    op.drop_index(op.f('ix_solicitudes_deas_id'), table_name='solicitudes_deas')
    op.drop_table('solicitudes_deas')
    # ### end Alembic commands ###
