"""agregar campo a EspacioUser

Revision ID: 108e91a8a001
Revises: d6a2a5cbdfab
Create Date: 2023-09-21 20:55:22.767978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108e91a8a001'
down_revision: Union[str, None] = 'd6a2a5cbdfab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espacio_user', sa.Column('pendiente', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('espacio_user', 'pendiente')
    # ### end Alembic commands ###
