"""Agregar fecha vencimiento a la provincia

Revision ID: 2294f59914e4
Revises: ebb32dd1589f
Create Date: 2023-09-20 18:49:46.235207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2294f59914e4'
down_revision: Union[str, None] = 'ebb32dd1589f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provincias', sa.Column('meses_duracion_certificado', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provincias', 'meses_duracion_certificado')
    # ### end Alembic commands ###
