"""Manejar fecha vencimiento certificado en el eo

Revision ID: 2f5ca058530b
Revises: 2294f59914e4
Create Date: 2023-09-20 18:51:56.936137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5ca058530b'
down_revision: Union[str, None] = '2294f59914e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espacios_obligados', sa.Column('cardio_asistido_vence', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('espacios_obligados', 'cardio_asistido_vence')
    # ### end Alembic commands ###
