"""Agregar dias al vencimiento del certificado por provincia

Revision ID: 460d8aaeefa4
Revises: d983986a407e
Create Date: 2023-09-23 20:34:07.245086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "460d8aaeefa4"
down_revision: Union[str, None] = "d983986a407e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "provincias",
        sa.Column("dias_duracion_certificado", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provincias", "dias_duracion_certificado")
    # ### end Alembic commands ###
