"""agregar columna valida a relacion user_espacio_obligado

Revision ID: 4e2ef7a28b05
Revises: c3a1fca81eb6
Create Date: 2023-09-20 15:35:50.905200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2ef7a28b05'
down_revision: Union[str, None] = 'c3a1fca81eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_espacio_association', sa.Column('valida', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_espacio_association', 'valida')
    # ### end Alembic commands ###
