"""borrar tablas erroneas

Revision ID: 54587fd93df5
Revises: d02de0c84d8d
Create Date: 2023-11-09 15:26:37.094109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54587fd93df5"
down_revision: Union[str, None] = "d02de0c84d8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Usamos el modo batch para SQLite
    with op.batch_alter_table("muertes_subitas", schema=None) as batch_op:
        # Paso 1: Agregar nuevas columnas sin restricción UNIQUE y con nullable=False
        batch_op.add_column(
            sa.Column(
                "espacio_obligado_id_temp", sa.Integer, nullable=True, unique=False
            )
        )
        batch_op.add_column(
            sa.Column("responsable_id_temp", sa.Integer, nullable=True, unique=False)
        )

    # Paso 2: Copiar los datos
    op.execute(
        "UPDATE muertes_subitas SET espacio_obligado_id_temp = espacio_obligado_id"
    )
    op.execute("UPDATE muertes_subitas SET responsable_id_temp = responsable_id")

    with op.batch_alter_table("muertes_subitas", schema=None) as batch_op:
        # Paso 3: Eliminar la columna antigua
        batch_op.drop_column("espacio_obligado_id")
        batch_op.drop_column("responsable_id")

        # Paso 4: Renombrar la nueva columna al nombre antiguo
        batch_op.alter_column(
            "espacio_obligado_id_temp", new_column_name="espacio_obligado_id"
        )
        batch_op.alter_column("responsable_id_temp", new_column_name="responsable_id")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('solicitudes_deas', sa.Column('atendido', sa.BOOLEAN(), nullable=True))
    # op.drop_constraint(None, 'reparaciones_deas', type_='foreignkey')
    # op.alter_column('reparaciones_deas', 'dea_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # # ### end Alembic commands ###
    pass
