"""agregar declaracion_jurada a espacio

Revision ID: 72c93d4a7328
Revises: c2aafaefbfb7
Create Date: 2023-09-19 21:28:00.069496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c93d4a7328'
down_revision: Union[str, None] = 'c2aafaefbfb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espacios_obligados', sa.Column('ddjj_personal_capacitado', sa.Boolean(), nullable=True))
    op.add_column('espacios_obligados', sa.Column('ddjj_senaletica_adecuada', sa.Boolean(), nullable=True))
    op.add_column('espacios_obligados', sa.Column('ddjj_protocolo_accion', sa.String(), nullable=True))
    op.add_column('espacios_obligados', sa.Column('ddjj_sistema_energia_media', sa.String(), nullable=True))
    op.add_column('espacios_obligados', sa.Column('ddjj_cantidad_deas', sa.Integer(), nullable=True))
    op.drop_column('espacios_obligados', 'ddjj_id')
    op.drop_column('espacios_obligados', 'declaracion_jurada_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espacios_obligados', sa.Column('declaracion_jurada_id', sa.INTEGER(), nullable=True))
    op.add_column('espacios_obligados', sa.Column('ddjj_id', sa.INTEGER(), nullable=False))
    op.drop_column('espacios_obligados', 'ddjj_cantidad_deas')
    op.drop_column('espacios_obligados', 'ddjj_sistema_energia_media')
    op.drop_column('espacios_obligados', 'ddjj_protocolo_accion')
    op.drop_column('espacios_obligados', 'ddjj_senaletica_adecuada')
    op.drop_column('espacios_obligados', 'ddjj_personal_capacitado')
    # ### end Alembic commands ###
