"""agregar reparacion_dea

Revision ID: 7bea75a4a1f5
Revises: b0100c4674ce
Create Date: 2023-09-19 17:51:34.830481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bea75a4a1f5'
down_revision: Union[str, None] = 'b0100c4674ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('solidario', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_ultimo_mantenimiento', sa.DateTime(), nullable=True),
    sa.Column('espacio_obligado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['espacio_obligado_id'], ['espacios_obligados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_obligado_id')
    )
    op.create_index(op.f('ix_deas_id'), 'deas', ['id'], unique=False)
    op.create_index(op.f('ix_deas_marca'), 'deas', ['marca'], unique=False)
    op.create_index(op.f('ix_deas_modelo'), 'deas', ['modelo'], unique=False)
    op.create_index(op.f('ix_deas_nombre'), 'deas', ['nombre'], unique=False)
    op.create_index(op.f('ix_deas_numero_serie'), 'deas', ['numero_serie'], unique=True)
    op.create_table('reparaciones_deas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('tecnico', sa.String(), nullable=True),
    sa.Column('dea_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dea_id'], ['deas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dea_id')
    )
    op.create_index(op.f('ix_reparaciones_deas_id'), 'reparaciones_deas', ['id'], unique=False)
    op.create_index(op.f('ix_reparaciones_deas_tecnico'), 'reparaciones_deas', ['tecnico'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reparaciones_deas_tecnico'), table_name='reparaciones_deas')
    op.drop_index(op.f('ix_reparaciones_deas_id'), table_name='reparaciones_deas')
    op.drop_table('reparaciones_deas')
    op.drop_index(op.f('ix_deas_numero_serie'), table_name='deas')
    op.drop_index(op.f('ix_deas_nombre'), table_name='deas')
    op.drop_index(op.f('ix_deas_modelo'), table_name='deas')
    op.drop_index(op.f('ix_deas_marca'), table_name='deas')
    op.drop_index(op.f('ix_deas_id'), table_name='deas')
    op.drop_table('deas')
    # ### end Alembic commands ###
