"""nueva relacion espacio usuario

Revision ID: 8eb4b5219385
Revises: 2f5ca058530b
Create Date: 2023-09-21 20:14:27.864693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb4b5219385'
down_revision: Union[str, None] = '2f5ca058530b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espacio_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('espacio_id', sa.Integer(), nullable=False),
    sa.Column('valida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios_obligados.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'espacio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('espacio_user')
    # ### end Alembic commands ###
