"""agregar visita

Revision ID: 8fa2e2540f39
Revises: 7bea75a4a1f5
Create Date: 2023-09-19 17:56:05.090099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa2e2540f39'
down_revision: Union[str, None] = '7bea75a4a1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=False),
    sa.Column('espacio_obligado_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("resultado IN ('Aprobado', 'Rechazado', 'Dado de baja')"),
    sa.ForeignKeyConstraint(['espacio_obligado_id'], ['espacios_obligados.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_obligado_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_visitas_id'), 'visitas', ['id'], unique=False)
    op.create_index(op.f('ix_visitas_observaciones'), 'visitas', ['observaciones'], unique=False)
    op.create_index(op.f('ix_visitas_resultado'), 'visitas', ['resultado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitas_resultado'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_observaciones'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_id'), table_name='visitas')
    op.drop_table('visitas')
    # ### end Alembic commands ###
