"""Descripción de la migración

Revision ID: a24fc1678b33
Revises: cf43a2fb5a58
Create Date: 2023-09-26 19:31:14.819357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24fc1678b33'
down_revision: Union[str, None] = 'cf43a2fb5a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_deas_id'), 'deas', ['id'], unique=False)
    op.create_index(op.f('ix_deas_marca'), 'deas', ['marca'], unique=False)
    op.create_index(op.f('ix_deas_modelo'), 'deas', ['modelo'], unique=False)
    op.create_index(op.f('ix_deas_nombre'), 'deas', ['nombre'], unique=False)
    op.create_index(op.f('ix_deas_numero_serie'), 'deas', ['numero_serie'], unique=True)
    op.create_index(op.f('ix_visitas_id'), 'visitas', ['id'], unique=False)
    op.create_index(op.f('ix_visitas_observaciones'), 'visitas', ['observaciones'], unique=False)
    op.create_index(op.f('ix_visitas_resultado'), 'visitas', ['resultado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitas_resultado'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_observaciones'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_id'), table_name='visitas')
    op.drop_index(op.f('ix_deas_numero_serie'), table_name='deas')
    op.drop_index(op.f('ix_deas_nombre'), table_name='deas')
    op.drop_index(op.f('ix_deas_modelo'), table_name='deas')
    op.drop_index(op.f('ix_deas_marca'), table_name='deas')
    op.drop_index(op.f('ix_deas_id'), table_name='deas')
    # ### end Alembic commands ###
