"""agregar espacio obligado

Revision ID: b31b96b6516a
Revises: 39795819626f
Create Date: 2023-09-19 17:47:03.918538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31b96b6516a'
down_revision: Union[str, None] = '39795819626f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espacios_obligados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("estado IN ('En proceso de ser Cardio-Asistido', 'Cardio-Asistido con DDJJ', 'Cardio-Asistido Certificado')"),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sede_id')
    )
    op.create_index(op.f('ix_espacios_obligados_estado'), 'espacios_obligados', ['estado'], unique=False)
    op.create_index(op.f('ix_espacios_obligados_id'), 'espacios_obligados', ['id'], unique=False)
    op.create_index(op.f('ix_espacios_obligados_nombre'), 'espacios_obligados', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_espacios_obligados_nombre'), table_name='espacios_obligados')
    op.drop_index(op.f('ix_espacios_obligados_id'), table_name='espacios_obligados')
    op.drop_index(op.f('ix_espacios_obligados_estado'), table_name='espacios_obligados')
    op.drop_table('espacios_obligados')
    # ### end Alembic commands ###
