"""agregar bool para manejar el vencido

Revision ID: c6d02cb491e8
Revises: a24fc1678b33
Create Date: 2023-09-26 20:54:48.972749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d02cb491e8'
down_revision: Union[str, None] = 'a24fc1678b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espacios_obligados', sa.Column('cardio_asistido_vencido', sa.Boolean(), nullable=True))
    op.drop_column('espacios_obligados', 'temp_estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espacios_obligados', sa.Column('temp_estado', sa.VARCHAR(), nullable=True))
    op.drop_column('espacios_obligados', 'cardio_asistido_vencido')
    # ### end Alembic commands ###
