"""nueva relacion espacio usuario234

Revision ID: d6a2a5cbdfab
Revises: 0752bd582f0c
Create Date: 2023-09-21 20:20:01.833491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a2a5cbdfab'
down_revision: Union[str, None] = '0752bd582f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
