"""agregar muerte_subita

Revision ID: d95dfc782bdb
Revises: dbb767662561
Create Date: 2023-09-19 21:11:05.535212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95dfc782bdb'
down_revision: Union[str, None] = 'dbb767662561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muertes_subitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('fallecio', sa.Boolean(), nullable=True),
    sa.Column('rcp', sa.Boolean(), nullable=True),
    sa.Column('tiempo_rcp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('espacio_obligado_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("sexo IN ('Masculino', 'Femenino', 'X')"),
    sa.ForeignKeyConstraint(['espacio_obligado_id'], ['espacios_obligados.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['responsables_sedes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_obligado_id'),
    sa.UniqueConstraint('responsable_id')
    )
    op.create_index(op.f('ix_muertes_subitas_edad'), 'muertes_subitas', ['edad'], unique=False)
    op.create_index(op.f('ix_muertes_subitas_id'), 'muertes_subitas', ['id'], unique=False)
    op.create_index(op.f('ix_muertes_subitas_sexo'), 'muertes_subitas', ['sexo'], unique=False)
    op.create_index(op.f('ix_muertes_subitas_tiempo_rcp'), 'muertes_subitas', ['tiempo_rcp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_muertes_subitas_tiempo_rcp'), table_name='muertes_subitas')
    op.drop_index(op.f('ix_muertes_subitas_sexo'), table_name='muertes_subitas')
    op.drop_index(op.f('ix_muertes_subitas_id'), table_name='muertes_subitas')
    op.drop_index(op.f('ix_muertes_subitas_edad'), table_name='muertes_subitas')
    op.drop_table('muertes_subitas')
    # ### end Alembic commands ###
