"""agregar campo a EspacioUser fecha

Revision ID: d983986a407e
Revises: 108e91a8a001
Create Date: 2023-09-21 21:00:12.597259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd983986a407e'
down_revision: Union[str, None] = '108e91a8a001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espacio_user', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('espacio_user', 'fecha_creacion')
    # ### end Alembic commands ###
