"""Agregar fecha_de_cardio_asistido

Revision ID: ebb32dd1589f
Revises: bec3af1df6ed
Create Date: 2023-09-20 18:46:27.481065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb32dd1589f'
down_revision: Union[str, None] = 'bec3af1df6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espacios_obligados', sa.Column('cardio_asistido_desde', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('espacios_obligados', 'cardio_asistido_desde')
    # ### end Alembic commands ###
