"""nueva relacion espacio usuario2

Revision ID: f90f718af1f6
Revises: 8eb4b5219385
Create Date: 2023-09-21 20:16:02.774804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90f718af1f6'
down_revision: Union[str, None] = '8eb4b5219385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
